### PR TITLE
Fix Rope.lines() iterator

### LINKED ISSUE #31: Rope.lines() is probably broken
I don't have tests for this yet, but I'm fairly certain I've found a case where `Rope`'s `.lines()` iterator won't do the right thing. Since our current implementation works by calling `.lines()` on every leaf node's internal `String` and then `chain()`s  the resultant iterators together, it'll split a line in half if the line spans the boundary between two nodes.

### LINKED ISSUE #32: Consider chunking the string in `Rope::from(String)`
Currently, when we create a new Rope from a String, we put the whole string in one `Leaf` node. That means that indexing-based operations will initially have roughly the same time overhead as indexing a String, and we won't see performance improvements until the Rope has been `append`ed or `insert`ed into enough to turn it into a nice tree structure. We might want to consider having the `Rope::from<String>` implementation split the string into chunks so that we can reap Rope performance benefits immediately.

### LINKED ISSUE #51: Split `Rope` nodes on newlines & store line counts

### LINKED ISSUE #52: Indexing ropes with Unicode characters is Wildly Broken
I was working on adding some QuickCheck property tests for `Rope`s, and I wrote two tests to ensure that `Rope` insert behaviour is equivalent to `String` insert behaviour. 

Unfortunately, these tests revealed an unrelated issue: when QuickCheck generates a string containing Unicode characters, `Rope`'s indexing operation in `Rope.split()` panics.

Here are a handful of the panics (it tried a _lot_ of weird strings, so I'm only attaching the first couple): 
```
---- test::properties::rope_insert_is_string_insert stdout ----
        thread 'test::properties::rope_insert_is_string_insert' panicked at 'index 0 and/or 9 in `¨T=/%�𞹧*jL~1ju츿瑞2⠇3*〗򸨋F+ຘ⁆숥⁧G0𦏦𦏦^┏n䘧Y]c,”¥h䱤^‟굃…7‧[2�
                                                           &›몍% G=‑ª؜S񖤰A櫾2|򮁺|?(¢惐6􏿿򽑤 ‹` do not lie on character boundary', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/str/mod.rs:1754
thread 'test::properties::rope_insert_is_string_insert' panicked at 'index 0 and/or 9 in `”¥h䱤^‟굃…7‧[2�
  &›몍% G=‑ª؜S񖤰A櫾2|򮁺|?(¢惐6􏿿򽑤 ‹` do not lie on character boundary', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/str/mod.rs:1754
thread 'test::properties::rope_insert_is_string_insert' panicked at 'index 0 and/or 9 in `”¥h䱤^‟굃…7‧[2�
  &›몍% ‹` do not lie on character boundary', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/str/mod.rs:1754
thread 'test::properties::rope_insert_is_string_insert' panicked at 'index 0 and/or 9 in `”¥h䱤^‟굃…7‧‹` do not lie on character boundary', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/str/mod.rs:1754
thread 'test::properties::rope_insert_is_string_insert' panicked at 'index 0 and/or 9 in `^‟굃…7‧‹` do not lie on character boundary', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/str/mod.rs:1754
thread 'test::properties::rope_insert_is_string_insert' panicked at 'index 0 and/or 9 in `…7‧‹` do not lie on character boundary', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/str/mod.rs:1754
thread 'test::properties::rope_insert_is_string_insert' panicked at 'index 0 and/or 9 in `ဓ7‧‹` do not lie on character boundary', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/str/mod.rs:1754
thread 'test::properties::rope_insert_is_string_insert' panicked at 'index 0 and/or 9 in `ࠊ7‧‹` do not lie on character boundary', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/str/mod.rs:1754
thread 'test::properties::rope_insert_is_string_insert' panicked at 'index 0 and/or 9 in `ࠂ7‧‹` do not lie on character boundary', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/str/mod.rs:1754
thread 'test::properties::rope_insert_is_string_insert' panicked at 'index 0 and/or 9 in `ࠀ7‧‹` do not lie on character boundary', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/str/mod.rs:1754
thread 'test::properties::rope_insert_is_string_insert' panicked at 'index 0 and/or 9 in `ࠀ‧‹` do not lie on character boundary', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/str/mod.rs:1754
thread 'test::properties::rope_insert_is_string_insert' panicked at 'index 0 and/or 9 in `ࠀန‹` do not lie on character boundary', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/str/mod.rs:1754
thread 'test::properties::rope_insert_is_string_insert' panicked at 'index 0 and/or 9 in `ࠀࠊ‹` do not lie on character boundary', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/str/mod.rs:1754
thread 'test::properties::rope_insert_is_string_insert' panicked at 'index 0 and/or 9 in `ࠀࠂ‹` do not lie on character boundary', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/str/mod.rs:1754
thread 'test::properties::rope_insert_is_string_insert' panicked at 'index 0 and/or 9 in `ࠀࠀ‹` do not lie on character boundary', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/str/mod.rs:1754
thread 'test::properties::rope_insert_is_string_insert' panicked at 'index 0 and/or 9 in `ࠀࠀဝ` do not lie on character boundary', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/str/mod.rs:1754
thread 'test::properties::rope_insert_is_string_insert' panicked at 'index 0 and/or 9 in `ࠀࠀࠏ` do not lie on character boundary', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/str/mod.rs:1754
thread 'test::properties::rope_insert_is_string_insert' panicked at 'index 0 and/or 9 in `ࠀࠀࠇ` do not lie on character boundary', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/str/mod.rs:1754
thread 'test::properties::rope_insert_is_string_insert' panicked at 'index 0 and/or 9 in `ࠀࠀࠃ` do not lie on character boundary', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libc
``` 
Obviously we are not currently handling grapheme indices properly.

### PR DESCRIPTION
**Pull request by hawkw**
This PR fixes the `Rope.lines()` iterator. It also adds @twisted-pear's code for line indexing and splitting, and a preliminary version of `Measure`.

Some of these features are still in development, but I want to get the fixed `lines()` iterator merged into master.

I think this supersedes PR #55 but I should make sure before closing it.

This should push patch v0.0.3 when it lands, since it fixes #31.

Closes #51 (@twisted-pear)
Closes #52 (@hawkw)
Closes #32 (@twisted-pear)
Closes #31 (@hawkw)

### CODE REVIEW

**Comment by twisted-pear** [comment]
i looked it over briefly, it looks fine to me

**Review by twisted-pear — APPROVED** [review]
it looks good to me, only reason i see not to merge it would be if we want to address #57 first

**Comment by hawkw** [comment]
I think I'd like to get this merged before starting #57, I'd rather not have broken code on master. Even though I know we don't have anyone downstream of us, it seems like a bad habit. 

There is a lot in this PR that will want to be refactored, though; I hacked together a lot of it in a hurry.

**Comment by hawkw** [comment]
Also, I think we're going to want to rewrite the `split_whitespace` iterator as well, since I suspect it'll have the same bug as `lines`, but that's its own issue.

**Pull request merged**
