### PR TITLE
#78 replaced all instances of or_zero! with saturating_sub

### LINKED ISSUE #78: Replace or_zero macro with saturating_sub
There are [a](https://github.com/an-cabal/an-rope/blob/0005d548856ea53e78f57295ed5ea3b89da7672b/src/internals/node.rs#L108-L109) [number](https://github.com/an-cabal/an-rope/blob/0005d548856ea53e78f57295ed5ea3b89da7672b/src/internals/node.rs#L115) [of](https://github.com/an-cabal/an-rope/blob/0005d548856ea53e78f57295ed5ea3b89da7672b/src/metric.rs#L280) [places](https://github.com/an-cabal/an-rope/blob/0005d548856ea53e78f57295ed5ea3b89da7672b/src/metric.rs#L298) where we use a macro, [`or_zero!`](https://github.com/an-cabal/an-rope/blob/b1677bba8b8dbaec007e3bdb36b42146d1ff8158/src/lib.rs#L45-L47), to subtract two unsigned numbers and return zero rather than overflowing if the result is less than zero. This is the same behaviour as the [`saturating_sub()`](https://doc.rust-lang.org/std/primitive.usize.html#method.saturating_sub) function in the standard library.

It'd be nice if instances of this macro could be replaced with `saturating_sub()`, as this is more idiomatic and might be faster on some platforms (if the CPU has a saturating subtraction operation, it could use an intrinsic...).

Once all uses of `or_zero!` are replaced, the macro definition can also be removed.

### PR DESCRIPTION
**Pull request by mclark4386**
Should resolve #78! Please let me know if you would like me to tweak or change anything!

### CODE REVIEW

**Review by hawkw — APPROVED** [review]
Looks good to me!

**Comment by hawkw** [comment]
Hi @mclark4386, this looks good, thank you!

For the future, if you're planning on making more commits to this project, I'd like to ask you to try to follow our [commit message conventions](https://github.com/an-cabal/an-rope/blob/master/CONTRIBUTING.md#commit-messages). In this case, I can just merge your PR with a conforming commit message, but in the future, if you open a PR with several commits, I'd like them to be correctly formatted before merging.

**Comment by hawkw** [comment]
@rachlmac, since this issue was originally assigned to you, I'd like to make sure you're okay with me merging @mclark4386's changes?

**Comment by rachlmac** [comment]
@hawkw @mclark4386 That sounds good to me, thank you for your help with this one!

**Comment by hawkw** [comment]
And merged, thanks @mclark4386! Please feel free to check out any other issues, if you like.

**Comment by mclark4386** [comment]
@hawkw @rachlmac Sorry about the incorrect formatting on the commit message. I did think about the format of the code, but didn't even cross my mind to be mindful of the commit message. Thank you for the critic and accepting the patch!

**Pull request merged**
